### ISSUE TITLE
User-selectable set of tags to be auto-tagging newly added spots

### ISSUE THREAD

**Issue by xulman** [mastodon-sc/mastodon#126]
this was motivated in the context of collaborative tracking: a user wanted to auto-tag spots that he/she has added,
this is an extension of the original idea (which was: added linked spots inherit tags from the source spot)

the auto-tagging set is empty by default

**Comment by tinevez** [comment]
Ok I see the application. 
I would suggest then we put this option in the tag table UI, with a single checkbox that states something like `Automatically tag next spots with:`

**Comment by tinevez** [comment]
Hello @xulman 

This issue relates to an enhancement, but there has been no work on it since quite some time. Are you ok to close it for now?

**Comment by xulman** [comment]
Sounds like an easy job, pity I failed to develop a PR for this... probably wasn't that urgent.
Agreed, let's clean up, closing it.
