### ISSUE TITLE
Ability to lock "I'm happy with" spots - make them uneditable.

### ISSUE THREAD

**Issue by xulman** [mastodon-sc/mastodon#127]
...to prevent from accidental position adjustment or removal,
locking involves all edges that link between two locked spots

use-case: Have to sets of spots -- fixed well-tracked set of spots and WIP set of spots

**Comment by tinevez** [comment]
I would do that with a special, built-in tag `locked`.
The implementation issue I see is that it may kill the generality of some components (the core stuff like editing do not know about tag, features etc).

**Comment by xulman** [comment]
Changing the underlying model would trigger an avalanche of issues in downstream apps, I agree. You, @tinevez , are working on a certain overhaul in Mastodon, an overhaul that will require the attention of the downstream apps anyway. Still, I don't think this is the right occasion to change the model too (two changes cumulated...). So, you're right, let's close it for now.

I like the idea of building up the Mastodon etiquette that, e.g., tags of certain names are supposed not to be modified. Speaking now of a built-in `TagSet` with special-purpose `Tag`s that "nice plugins" would honor and obey.
