### ISSUE TITLE
MIN_RADIUS is sometimes too large

### ISSUE THREAD

**Issue by ksugar** [mastodon-sc/mastodon#142]
## Issue
`MIN_RADIUS` can prevent us from adjusting the spot size to a tiny object.

## Investigation
Currently, `MIN_RADIUS` is hard-coded [here](https://github.com/mastodon-sc/mastodon/blob/mastodon-1.0.0-beta-21/src/main/java/org/mastodon/views/bdv/overlay/EditBehaviours.java#L111) to `1.0`, which can be too large sometimes.

## Suggestion
- make it customizable from `Preferences`
- change the value of `MIN_RADIUS` to `0.0` or very small value

**Comment by tinevez** [comment]
Could we make it adapt to the min pixel size?

**Comment by ksugar** [comment]
I think it's a good idea to set the value to the equivalent of 1 pixel.

**Comment by tinevez** [comment]
Fixed with https://github.com/mastodon-sc/mastodon/pull/163
