### ISSUE TITLE
TrackScheme Hierarchy improvements

### ISSUE THREAD

**Issue by maarzt** [mastodon-sc/mastodon#172]
Improve the rendering of the hierarchy view, to make it easier to grasp to structure of the lineage:

- [x] Display the node labels, not inside the circle, but below or next to the circle.
      (The circle visualizing the nodes are usual not big enough to show the node label.)
- [x] Have wider lines (~2 or 3 pixels) connecting the nodes.
- [x] None curved lines. (I'm sorry! The curves are BEAUTIFUL. But they visually confuse me to much.)
- [x] Restrict the hierarchy view to only show one sub-tree of the branch graph. The biologists are often only interested in one particular cell, and how it divides. So the would love to focus on this one cell, and only show its lineage.

**Comment by tinevez** [comment]
Quite some work :)
Do you feel like working on it?

**Comment by maarzt** [comment]
@tinevez Yes, I'm indeed already working on some of these points.

**Comment by tinevez** [comment]
All done!
The issue with the node size the branch TrackScheme is the subject of another issue, the resolving of which is postponed.
