### ISSUE TITLE
Branch Graph TrackScheme functionality gets lost after a `BranchGraph.graphRebuilt()`

### ISSUE THREAD

**Issue by maarzt** [mastodon-sc/mastodon#176]
I noticed the problem with the newly added branch graph and hierarchy track scheme. After changing the `ModelGraph`, by [removing and adding edges](https://github.com/mastodon-sc/mastodon-tomancak/blob/a51d94e8985c3cbc9ab9c094e06fba0cfce683fc/src/main/java/org/mastodon/mamut/tomancak/FlipDescendants.java#L79-L80), and triggering a `BranchGraphSynchronizer.graphRebuilt()` the branch graph TrackScheme loses parts of it's functionality:
1. The arrow keys (left, right, up, down) are no longer responsive. (This issue likely also affects the [dev branch](https://github.com/mastodon-sc/mastodon/tree/dev))
2. And the view does not update, whenever there is only downward track shown, see https://github.com/mastodon-sc/mastodon/pull/174.

**Comment by tinevez** [comment]
Tested on my Mac.

Things work in the `dev` branch. In the `branch-graph-rendering` things work also provided that the special display mode (display only track below) is not selected.

 But indeed, if we select 'display tracks downward' and modify the graph, then the bug described above happens. Interestingly, it goes away if we switch back to the normal view.

**Comment by tinevez** [comment]
It seems that it is the focus and/or highlight system that is fscked up.

**Comment by maarzt** [comment]
This issue is fixed in commit https://github.com/mastodon-sc/mastodon/pull/174/commits/0a015af1f1afab10e62e455a059d53ecac688ad6
