### ISSUE TITLE
Every new projects obtains automatically internall UUID code...

### ISSUE THREAD

**Issue by xulman** [mastodon-sc/mastodon#180]
...that would work merely like an authentication token.

Motivated by: https://github.com/mastodon-sc/mastodon-collaborative/issues/16

Use cases:
- If I share a `.mastodon` file with someone and get it back edited, I can check if it is the original project.
- If client-server collaborating env is established, clients can be warned when talking to a server hosting data of a different project
- Mastodon plugins can benefit from maps: UUID -> {set of various settings of that plugin} ([like here](https://github.com/mastodon-sc/mastodon-ext-viewers/blob/master/src/main/java/cz/it4i/ulman/transfers/graphexport/ui/util/PerProjectPrefsService.java)), e.g. prefilled GUI params per project ([e.g., here](https://github.com/mastodon-sc/mastodon-ext-viewers/blob/ea5fa96726594217b361677897d82c06ef3383db/src/main/java/cz/it4i/ulman/transfers/graphexport/leftrightness/ui/SlicesSorterDlg.java#L49-L88))

**Comment by tinevez** [comment]
Hello @xulman 

This issue relates to an enhancement, but there has been no work on it since quite some time. Are you ok to close it for now?

**Comment by stefanhahmann** [comment]
This may be relevant for https://github.com/mastodon-sc/mastodon-tomancak/issues/15
Thus at least hereby I would like to make the link to that other issue.

**Comment by xulman** [comment]
I would put this on the roadmap of [reworking app model](https://imagesc.zulipchat.com/#narrow/stream/327470-Mastodon/topic/Reworking.20the.20app.20model), so that the new (forgot the class name, so making up one now) `MastodonProject` main class would offer two methods
- `getProjectID()` - firm ID, immutable, created random when a project is saved for the first time (created)
- `getProjectHash()` - reflects on the current content of the project, can be used to detect if something has changed (e.g. after running some other plugins), this method would merely collect `hash()` from "important data structures"

**Comment by tinevez** [comment]
I suggest to defer this until the renewal of the `collaborative` project.
