### ISSUE TITLE
observed UX: The open recent text area in the Mastodon main window could be editable 

### ISSUE THREAD

**Issue by xulman** [mastodon-sc/mastodon#181]
Sometime one has multiple `.mastodon` projects nearby in otherwise deeply nested common folder, one clicks all the way to open the first project.. later one wants to open the second project... and must click through again (or Cut&Paste the path, edit aside, open dialog, Paste-in the edited path, choose `.mastodon` file)

Normal people, who don't mess with the text area, would hopefully not mind that it is editable...

**Comment by tinevez** [comment]
Do you feel like working on this? We are already late for the beta-22...

**Comment by xulman** [comment]
![Screenshot_20220727_155249](https://user-images.githubusercontent.com/10509335/181264430-c34dd623-8550-4e26-9dcb-360c67da71b2.png)
was easy... if'd like it... but **does not** need to go into beta-22

(need to test on other platforms, need to figure the alignments... and even fonts may be less heavy)

**Comment by xulman** [comment]
rather then editing the text area, I thought it is easier to open the containing folder, navigate UI-wise to the nearby project and then drag&drop to open it

would be nice, btw, to be able to DnD into the laucher

**Comment by xulman** [comment]
the code would be here: https://github.com/xulman/mastodon/commit/8e7dbd660a8e38d42b24b52704242abc812237a8

**Comment by tinevez** [comment]
It's good, but please make sure the edited paths are serialized to the list of recent projects after edit.

**Comment by maarzt** [comment]
I'm not sure after reading the commits. With the newest Mastodon version, double clicking on the filename in the Mastodon launcher opens a file open dialog. That's a nice solution already. Should this issue therefor be considered fixed? @xulman could you comment.

@stefanhahmann would otherwise work on this issue. He would make the text area editable, as suggested in this issue.
