### ISSUE TITLE
observed UX: People are not using tags because they don't know to assign them

### ISSUE THREAD

**Issue by xulman** [mastodon-sc/mastodon#182]
I propose to introduce the set tag functionality reachable also from Mastodon menu... Currently it is only after pressing `y` (default key).

**Comment by xulman** [comment]
![](https://imagesc.zulipchat.com/user_uploads/16804/v1b-qyyXtcZY_pyvJlmIXnrt/Screenshot_20220727_111014.png)

Suggesting to
- (at least) rename Tags -> Assign Tags
- (potentially also) add menu item to educate users about the key short cut

(here the latter is illustrated with a very raw implementation... just WIP for the illustration)

**Comment by xulman** [comment]
the code for the renaming would be here: https://github.com/xulman/mastodon/commit/bc884d460833cf0a8d1acfa58a50dce7b8776317

**Comment by tinevez** [comment]
Already implemented.
