### ISSUE TITLE
Suggest Branch Graph Version 2

### ISSUE THREAD

**Issue by maarzt** [mastodon-sc/mastodon#189]
I think the branch graph functionality will be very important in Mastodon and I like it already very much. That's why I think will by very valuable to fix following problem now.

While playing around with the branch graph. I noticed that the branch graph always looks a bit different from what I expect from a biological point of view. Here is an example, I used a blue pen to draw an example for a tracking graph, and a red pen to draw the respective branch graph that mastodon generates:

### Currently: Branch Graph Version 1

<img src="https://user-images.githubusercontent.com/24407711/184321873-3ea6478c-5ed0-4028-880c-fe9d4183d8f6.png" width="400"/>

When I would describe what the blue graph shows it would go like this: "A cell divides into two cell, than they merge again, and then this cell divides again." *(I know cells don't merge, but other objects tracked with mastodon might merge)*

Please notice notice how the branch graph hardly tells this story. The initial cell is for some reasons represented by two nodes, than the first cell division is represented by two parallel edges. After merging we have again two nodes to represent one cell, and finally we see a clear cell division in the branch graph.

I know and understand how Mastodon calculates the branch graph. But I would like to make the point, that the resulting branch graph is hard to understand from a Biological point of view.

I would therefor suggest to change how the branch graph is defined and calculated in Mastodon. Here is my suggestion:

### Suggestion: Branch Graph Version 2
The nodes in the "branch graph version 2" represent a cell / spot that moves over time without dividing or merging. The edges in the "branch graph version 2" represent cell division or merging events.
<img src="https://user-images.githubusercontent.com/24407711/184321885-d52723b7-1397-42c2-beb8-28ed806aab78.png" width="400"/>

Advantages of version 2:
* It better shows the biological point of view.
* A cell is always represented by exactly on node in the branch graph.
* This will probably also make it easier to define biological relevant features on the branch graph.
* It is easier to write functionality like renaming a branch for this branch graph.

Disadvantages of version 2:
* Quite some work to again change the branch graph.
* It will be harder to to render the Branch TrackScheme such that it looks exactly like the normal TrackScheme.

**Comment by maarzt** [comment]
@tinevez What do you think?

**Comment by tinevez** [comment]
Thanks for this suggestion!

Yes you are right the v2 shows better the biology. 
But for now, I would be in favor of keeping the version 1 of the model, mainly because of the amount of work to get it right again. Also because we do not have many applications of the loops in Biology. (Do we?).

What about we address the issue by working on the TrackScheme display of loops instead?

**Comment by tinevez** [comment]
Woah! Ok then let's go. 
Do you need RW access to the `mastodon-graph`-repo?

**Comment by maarzt** [comment]
Great. I can push already to `mastodon-graph`. I think Tobi added me as a member to the mastodon-sc organization.

**Comment by maarzt** [comment]
Hi @tinevez, I created two PRs that address this issue. It works well, except for the graph coloring with respect to branch graph, that's something that still needs to be fixed. But maybe that's a piece of :cake: for you? I don't yet understand the graph coloring well enough to fix it.

And I will be on vacation till September 6.
