### ISSUE TITLE
Implement drag'n'drop for the Mastodon launcher

### ISSUE THREAD

**Issue by maarzt** [mastodon-sc/mastodon#208]
## Use case
A user has Fiji, the Mastodon launcher and the file browser open on his computer. The user would like to open a mastodon project by dragging a *.mastodon file from the file browser to the Mastodon launcher.

## Acceptance criteria
Dragging a *.mastodon file via drag'n'drop from the file browser to the Mastodon laucher opens the mastodon project.

**Comment by tinevez** [comment]
Normally it is implemented in Mastodon. But if you do this in Fiji, there is a bug in Bioformats that prevents it to work. The error message is weird:

![Screenshot 2022-11-22 at 15 47 05](https://user-images.githubusercontent.com/3583203/203343863-59666a33-7a62-4051-a88a-231da2f38732.png)

**Comment by stefanhahmann** [comment]
Resolved by https://github.com/mastodon-sc/mastodon/pull/214
