### ISSUE TITLE
Grapher does not print values

### ISSUE THREAD

**Issue by stefanhahmann** [mastodon-sc/mastodon#212]
# Bug description

The grapher view does not plot values that are actually existing in the table view.

# Steps to reproduce the bug

1. Start Fiji
2. Start Plugin Mastodon
3. open Mastodon project grapher-bug.mastodon: https://cloudstore.zih.tu-dresden.de/index.php/s/XgbnqRDgb9jLXLb
4. Confirm dialog image data not accessible
5. Open grapher
6. Select "Spot position - X" for X axis
7. Select "Spot position - Y" for Y axis
8. Select "From context" - "full graph"
9. Press "Plot"
10. Check the result in the grapher view. No points are plotted in the diagram, even though the plot window is updated. It zooms to a location without data points. Giving the user the impression that there is no data available. 
 

# Additional information:

The way to zoom out is to first click on the plot and afterwards use `Shift+Crtl+Scroll` or `Z + Z` to zoom out. After successfully zooming out once, everything works nicely. 

![GIF 22 11 2022 12-33-23](https://user-images.githubusercontent.com/10515534/203322572-87c63d5c-952f-42ce-a232-24bc39cc7e99.gif)

# Version:
ImageJ 1.53t
Mastodon: 1.0.0-beta-26
Windows: 10 + Ubuntu 20.04 LTS

# Tasks:
- [ ] Reproduce bug
- [ ] Find reason
- [ ] Fix bug
- [ ] Add "Fit axes" button for convenience
- [ ] Optional: Make `Alt + Scroll` the same behaviour as `Shift+Ctrl+Scroll` ( `Alt+Scroll` currently is the same as `Ctrl+Scroll`, i.e. zooming on x-axis)

**Comment by tinevez** [comment]
I can get it to work:

![Screenshot 2022-11-22 at 15 40 13](https://user-images.githubusercontent.com/3583203/203342291-548c1901-eda4-40e7-b541-45cca1b756d0.png)

But I had to unzoom first, as the grapher window was showing the bottom left part of the plot, where there is no data point.

**Comment by maarzt** [comment]
> @stefanhahmann wrote:
> * When I set "From context" and "full graph" and press "Plot", the Grapher window makes an animation of the axes. This gives the user the impression that the Grapher window tries to zoom to the full extent of the data. I suggest to omit this behaviour, since it is a bit irritating. At least for me, it was not clear what happened during the animated adjustment of the axes.

I think there is indeed some bug. After opening a new grapher window, selecting "Spot - X", "Spot - Y", "From context: full graph" and clicking "Plot", the plot window is updated. But it **zooms to a location without data points**. Giving the impression that there is no data available. The way to zoom out is to first click on the plot and afterwards use ```Shift+Crtl+Scroll``` or ```Z``` + ```Z``` to zoom out. I myself couldn't find how to zoom out, despite knowing the short cuts. So I too got the impression, that the grapher window is buggy. After I successfully zoomed out once, everything worked really nicely. So there seems to be a problem only with the initial state after opening a new grapher window.

Let's try to fix the initial zoom state of the grapher window. And also add a "Fit axes" button for convenience.

**Comment by stefanhahmann** [comment]
Resolved via #349
