### ISSUE TITLE
Axes definition

### ISSUE THREAD

**Issue by stefanhahmann** [mastodon-sc/mastodon#216]
# User story

As a user of Mastodon, it would make interpretation of data easier, if it was possible to define a coordinate system within the project.
Features that can be computed on the dataset may then be clearer to be communicated/interpreted (e.g. directions of cell divisions, directions of cell movements).
The coordinate system should reflect the orientation of the organism within the dataset.

# Acceptance criteria

* Definition of 3 (orthogonal?) axes is possible via the user interface
  * Lateral - Lateral axis ("left" - "right", x-axis)  
  * Ventral - Dorsal axis ("front" - "rear", y-axis)
  * Animal - Vegetal axis ("top" - "bottom", z-axis)

# To be discussed

* Should there be one axes-definition per Tag-Set?
* User interaction to define axes within Mastodon

**Comment by tinevez** [comment]
Hello @stefanhahmann 

This definition seems to be specific to a certain class of imaging experiments and not super general. To this regard, would you agree to implement these features in a dedicated Mastodon plugin? That would have its own artifact?

**Comment by stefanhahmann** [comment]
To me this sound reasonable. How about a sub-project "mastodon-lineage-analysis"?
