### ISSUE TITLE
FixImagePath NPE on NewMastodonProject from ImageOpenedInImageJ

### ISSUE THREAD

**Issue by xulman** [mastodon-sc/mastodon#228]
...likely because there exists no project's xml yet

```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at org.mastodon.mamut.tomancak.DatasetPathDialog.<init>(DatasetPathDialog.java:107)
	at org.mastodon.mamut.tomancak.DatasetPathDialog.<init>(DatasetPathDialog.java:98)
	at org.mastodon.mamut.tomancak.TomancakPlugins.tweakDatasetPath(TomancakPlugins.java:397)
	at org.scijava.ui.behaviour.util.RunnableAction.actionPerformed(RunnableAction.java:47)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
```

The c'tor at L107 should be more smarter and test if it has gotten non-null project reference.

And if it got `null` ref, show a new dialog "sorry, no project yet, please save it first" (or alike) and avoid throwing NPE because indeed the issue is gone after the project is saved (tested myself).

**Comment by xulman** [comment]
(I apparently cannot assign the issue to myself, nor can I give it a label... but I'm okay with that, just FYI)

**Comment by tinevez** [comment]
How do you reproduce this bug? I have no error message when creating a project from an ImagePlus.

**Comment by xulman** [comment]
1. fresh Fiji
2. install Mastodon update site
3. open any TIFF into Fiji
4. open Mastodon
5. choose "new Mastodon project", then "use an image opened in ImageJ"
6. click "create", Mastodon opens normally
7. click File -> Fix Image Path
8. NPE comes out...

**Comment by tinevez** [comment]
Ahhhhhh I missed the last part.
Indeed: 
![image](https://user-images.githubusercontent.com/3583203/226210742-d5d1dacf-8f06-46c9-901e-230aa52b2503.png)

Do you want to work on it?

**Comment by xulman** [comment]
I can....

It breaks [here](https://github.com/mastodon-sc/mastodon-tomancak/blob/7b7d154a02ad7a5e00b43b966a758593c1e7073b/src/main/java/org/mastodon/mamut/tomancak/DatasetPathDialog.java#L107), I would solve it by adding a guarding-test before checking, e.g.,

```
if (project == null || project.getProjectRoot() == null) {
     code to create a different dialog content -- a content that informs
     that it cannot be fixing a path in a project when there's no project created yet
}
```
