### ISSUE TITLE
Load/Save BDV settings with Mastodon Load/Save

### ISSUE THREAD

**Issue by stefanhahmann** [mastodon-sc/mastodon#230]
# User Story

As a Mastodon user, I would like that any potential BigDataViewer (BDV) settings that I have made, are saved, when I save the Mastodon project. These settings could e.g. brightness and color settings.

Currently, the loading/saving of these settings is separated from the loading/saving procedure of a Mastodon project, cf.:

![grafik](https://user-images.githubusercontent.com/10515534/227567216-25f5331a-71aa-4d47-83cb-8c3262a60c73.png)

The likelyhood that a Mastodon users forgets about loading/saving the BDV settings extra to loading/saving the project is quite high and the current procedure also includes an additional step, that is not really required.

# Acceptance criteria

1. When the Mastodon project is saved the BDV settings are saved as well.
2. When the Mastodon project is loaded, existing BDV settings are loaded as well.

# Tasks
- [ ] 

# Additional information:

Settings made in Mastodon Big Data Viewer:
![grafik](https://user-images.githubusercontent.com/10515534/227184591-ccfbebe9-9035-40ec-a236-0565e165c38a.png)

Settings after saving the Mastodon project and re-opening it (while not extra saving/loading BDV settings)
![grafik](https://user-images.githubusercontent.com/10515534/227183510-01f231b7-c964-409d-83dd-e38ae65f63b4.png)

**Comment by stefanhahmann** [comment]
@tinevez can you please comment on this issue if it makes sense from your perspective? the issue came up while testing some things inside Mastodon with colleagues from MPI CBG

**Comment by tinevez** [comment]
Wait, normally the user settings are saved in a *.settings.xml file along with the data. And when the BDV image is loaded, Mastodon should load and apply the settings along. If it is not the case, then it is a bug.

**Comment by tinevez** [comment]
Actually this works. The `settings.xml` file is correctly reloaded when a BDV window is opened.

**Comment by stefanhahmann** [comment]
Hm, with the following workflow, I cannot get it work. Also with this workflow, no settings.xml is generated. I used this dataset for the purpose of demonstration: http://data.celltrackingchallenge.net/challenge-datasets/Fluo-N3DH-CE.zip

Since the workflow is quite long, I have recorded it. You can watch the recording here: https://cloudstore.zih.tu-dresden.de/index.php/s/3kAMJbmz5TySXKd

Please do not that at 1:54 of the video I make some BDV settings that are not remembered after I have saved the project, closed it, and reopened it, cf. 2:30 of the video.

Is it a user error that with this workflow no settings.xml is created?

**Comment by tinevez** [comment]
ah ok. It works with the beta-26
I will see what does not work with dev branch

**Comment by tinevez** [comment]
Heu wait. You have to manually save the `*.settings.xml` file. It is done in the `File` menu when a BDV view is active: `Save Bdv Settings`

![Screenshot 2023-03-24 at 13 20 15](https://user-images.githubusercontent.com/3583203/227519699-d1863e6e-957d-4135-8ffe-e8959ff3ee9d.png)

**Comment by stefanhahmann** [comment]
> ah ok. It works with the beta-26 I will see what does not work with dev branch

the video was actually recorded with the official Fiji and the beta-26 release of mastodon that was loaded from the update site.

**Comment by stefanhahmann** [comment]
> Heu wait. You have to manually save the `*.settings.xml` file. It is done in the `File` menu when a BDV view is active: `Save Bdv Settings`
> 
> ![Screenshot 2023-03-24 at 13 20 15](https://user-images.githubusercontent.com/3583203/227519699-d1863e6e-957d-4135-8ffe-e8959ff3ee9d.png)

Ah, I see. So, this is the trick.

**Comment by tinevez** [comment]
I think this is a good idea for Mastodon. People will forget about saving the settings when they close Mastodon, this would give persistance.

**Comment by stefanhahmann** [comment]
> I think this is a good idea for Mastodon. People will forget about saving the settings when they close Mastodon, this would give persistance.

Okay, I changed the description of the issue.

**Comment by tinevez** [comment]
The load part is normally done.
