### ISSUE TITLE
BDV Brightness Settings dialog cannot be opened anymore

### ISSUE THREAD

**Issue by stefanhahmann** [mastodon-sc/mastodon#285]
# Bug Description

The BDV brightness settings dialog cannot be opened anymore.
Also the keymapping for this action cannot be changed anymore.

### Method 1
1. Open a Mastodon project
2. Open the BDV view
3. Press "S". This should open the brightness settings dialog, but nothing happens

### Method 2
1. Open a Mastodon project
2. Open the Data table view
3. Menu > Settings > Brightness settings. This should open the brightness settings dialog, but nothing happens. The same applies to "visibility and grouping".

### KeyMapping
1. Open a Mastodon project
2. File > Preferences > Settings > KeyMap
3. Filter: brightness settings
4. Click on "brightness settings"
5. Change Binding to 'T'
6. Apply
7. Warnings appear and binding is not correctly updated: 

![grafik](https://github.com/mastodon-sc/mastodon/assets/10515534/e00ccd33-5ae8-4e62-a499-2f8a23b6e9b2)

**Comment by drchrisch** [comment]
Nice to read. I found the same behavior and thought it was due to a somewhat strange installation on my side. Didn't really found time to go deeper.

**Comment by stefanhahmann** [comment]
I made some investigations in the code. I assume that it has to do with this commit: https://github.com/mastodon-sc/mastodon/commit/9b824d816d60b3f96f3c4cc470cb75290ea6b8ad

However, the commit is really big and thus not easy to understand, where the relevant part is that is responsible for this bug.

**Comment by stefanhahmann** [comment]
Presumably, also this commit is related to that: https://github.com/mastodon-sc/mastodon/commit/7f75bdaa9c0c420e2717723b03b9086f347fcf3b

**Comment by tinevez** [comment]
I think this is not a bug: The dialogs you mention have been deprecated in BDV, and are to be removed in favor of the side pane.

**Comment by stefanhahmann** [comment]
Hm, okay. This leads me to 2 questions:

1. How would can user currently make the settings, he/she used to set via these dialogs in previous versions? I cannot see these settings in the BDV side pane (or at least, I cannot find them)?
2. Does it make sense that this command can still be configured in the BDV KeyMap settings of Mastodon? 
![grafik](https://github.com/mastodon-sc/mastodon/assets/10515534/18c1305a-51ef-4550-bb9d-f319b6cda24b)

**Comment by stefanhahmann** [comment]
> 1/ Honestly, I think these settings are gone. They cannot be set. This is a question for @tpietzsch involving the next version of BDV.

I found out how these settings can currently be made via the BDV Panel and a screenshot for further reference:

![grafik](https://github.com/mastodon-sc/mastodon/assets/10515534/abbda998-f189-409e-96d3-5901458cba69)

**Comment by stefanhahmann** [comment]
> 2/ Probably they can be removed.

I would say so. There is no need for a KeyMap setting for a function that does not exist anymore.

**Comment by stefanhahmann** [comment]
I agree that this is not a bug and close this issue in favor of #288
