### ISSUE TITLE
project with .xml pointing on TIFF series is not opening

### ISSUE THREAD

**Issue by xulman** [mastodon-sc/mastodon#293]
... fails openning:

![Snímek obrazovky 2024-03-12 182901](https://github.com/mastodon-sc/mastodon/assets/10509335/50812d1c-e7eb-4c53-81e8-83d19b61679f)

Some hard-coded casting of `SpimData` somewhere??

----
after converting the data into .hdf5, it went well.....

I know tiffs in conjunction with the `.xml` are considered evil (as they lack the features to foster a smooth viewing XP), but the same `.xml` file works *well* in plain BDV and even (!) opens the tiffs sufficienty fast (as they are small 2D images...)

**Comment by xulman** [comment]
(and I needed to open the image data, DUMMY wouldn't be enough.. as the ch02 contains *masks that I convert to spots-detections*, and then track-link using Mastodon... and then export back to CTC format)

**Comment by tinevez** [comment]
Hello. I cannot reproduce the problem with the beta-29.
I used the 'mitosis.tiff' example in Fiji, saved to my Desktop on Mac.
Re-opening the project works, provided that the TIFF file has been saved somewhere on the computer. 

<img width="544" alt="Screenshot 2024-03-13 at 17 02 36" src="https://github.com/mastodon-sc/mastodon/assets/3583203/1fc0ed4a-d052-4514-b9f2-87e82bcd3081">

**Comment by tinevez** [comment]
Hello @xulman 
Shall we pursue investigating this bug? I could not reproduce it but maybe I am not following the right way to do so.

**Comment by xulman** [comment]
This was really about having *xml+tiff* dataset (in contrast to the *xml+n5* or *xml+hdf5*). I'll check again against the latest beta-30 and either report here (and share example failing data) or close it here.

**Comment by xulman** [comment]
I actually haven't checked plain tiff in Fiji, I mean the variant Mastodon opened on the currently opened image in Fiji

**Comment by tinevez** [comment]
Works now.
