### ISSUE TITLE
Expected behaviour of Bdv Branch View

### ISSUE THREAD

**Issue by stefanhahmann** [mastodon-sc/mastodon#300]
I am wondering if the following is the expected behavior in the Bdv Branch View:

* Top left: TrackScheme
* Top right: TrackScheme Branch
* Lower left: Bdv
* Lower right: Bdv Branch

![GIF 27 03 2024 11-33-23](https://github.com/mastodon-sc/mastodon/assets/10515534/35e2cf6b-1314-4674-ab6a-a303d43cac88)

I would have expected that the Bdv Branch shows the spots that belong to each branch at all timepoints where spots of the respective branch exist. However, it seems that in the Bdv Branch view, it only shows the spot of the last timepoint and in all other timepoint nothing is shown.

If the latter is the intended behavior, I do not find this very intuitive, but there might be some reason that am I not aware of that the behavior is like this?

**Comment by stefanhahmann** [comment]
After talking to @maarzt it turns out that this is expected behavior.
However, we identified a new feature request and documented it here: https://github.com/mastodon-sc/mastodon/issues/301

**Comment by tinevez** [comment]
I think the branch BDV is only useful in movies with a very large number of time frames, with cells that divide a lot. It offers some lower granularity over time event, at the cost of accuracy. I am not sure it is as useful as the Branch TrackScheme
