### ISSUE TITLE
Move the import & export menu from the Plugins to the File menu.

### ISSUE THREAD

**Issue by tinevez** [mastodon-sc/mastodon#330]
So that with the 'naked' Mastodon, there are no items in the Plugins menu. 
Also import / export items are better in the File menu.

After this: make sure that all I&E plugins in other mastodon artifacts go in these menus.

**Comment by stefanhahmann** [comment]
https://docs.google.com/document/d/1-hC6YApjdD-58bYWdPDR8Pw3eIyOYTaT5Wtzlx9L-FQ/edit

**Comment by stefanhahmann** [comment]
![grafik](https://github.com/user-attachments/assets/a63dd4b8-efea-4765-af81-ec2e2a12b4bb)

**Comment by tinevez** [comment]
- [ ] do this in the core -> JY
- [ ] do this for plugins in `mastodon-pasteur` -> JY
- [ ] do this for plugins in `mastodon-tomancak` -> Mathias

**Comment by stefanhahmann** [comment]
Cf. #332
