### ISSUE TITLE
Intermediate "new project" dialog.

### ISSUE THREAD

**Issue by tpietzsch** [mastodon-sc/mastodon#53]
It is at the moment probably unclear to new users that the File Dialog popping up when "new project" is clicked means "Select a BDV file with image data". It would be good to instead have a dialog open, with a (appropriately) file field for the BDV file, and then once a fitting file was selected enabling "OK"/"Create project" button on the dialog.

**Comment by tpietzsch** [comment]
@tinevez I assigned this issue to you for now...

**Comment by tinevez** [comment]
I would instead completely remove the _Load project_ and _New project_ buttons from the Main window. All the buttons on this window are relative to editing or saving the current project. 

I would make separate commands to start a new project or load one, that would then launch and show the main window. From these commands we have then the leisure to make a clear and explicit GUI. I was thinking of something like I did for the TGMM import in MaMuT:

![capture](https://user-images.githubusercontent.com/3583203/37079654-9a50a9ae-21e3-11e8-861d-8b54912c139c.PNG)

**Comment by tpietzsch** [comment]
Yes, very good point!

I think the current MainWindow happened because we are starting it up stand-alone from Eclipse, not from the Fiji Plugins menu (as it will eventually be). In principle, I'm fine with removing those buttons and making a proxy Meta-MainWindow that serves as a launchpad when running stand-alone from Eclipse (could be an empty window with just the plugin menu entries). My feeling is that we should retain the capability to run stand-alone without bringing up Fiji. For one thing, it forces us to keep hygiene with dependencies. Mastodon (core) should be as self-contained as possible. scijava-common as a dependency is fine. imagej-common not so much...

I think this is a bigger change than it first looks, but I like this direction very much!

**Comment by tinevez** [comment]
You are totally right that Mastodon should be standalone. Actually I was thinking of distributing it with Icy as well. So no ImageJ-common there...

As you, rather than plugin commands I was thinking of a "welcome" GUI - or Meta-MainWindow -with just two buttons:
- New project.
- Load project.
Later, we can put some clever detection-fu scheme that finds in what context Mastodon was launched (standalone, Fiji, Icy) and decorates the meta-main-window. But let's do this laaaaaater.

**Comment by ctrueden** [comment]
> You are totally right that Mastodon should be standalone. Actually I was thinking of distributing it with Icy as well. So no ImageJ-common there...

Why can Icy not consume `imagej-common`?

Does `imagej-common` bring anything of value to the table for this project? If so, this dependency should be usable even in "standalone" mode. And if not for some reason, let's discuss.

**Comment by tpietzsch** [comment]
@ctrueden Just to clarify: I mentioned `imagej-common` as a random example. My point was to keep dependencies to a minimum. `scijava-common` is valuable to for the context/plugin system so we should have this as a dependency.
