### ISSUE TITLE
TS adds new timepoint beyond the dataset timepoints span

### ISSUE THREAD

**Issue by xulman** [mastodon-sc/mastodon#75]
- while annotating a dataset, move to the last timepoint,
- move mouse over some spot in BDV,
- press A (add linked spot) and it gets a bit crazy... would expect nothing to happen actually

TS seems to add another time point (a new line appears in TS) but does allow to see it (to scroll over it). BDV shows ellipses from the last time point and also from the new just-beyond time point. At least, this is what it looks like from outside.

How can I help?

**Comment by tinevez** [comment]
It's a plain bug. Linking from one spot to another spot in the next frame is forbidden and what you describe should amount to nothing happening.
